// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: version.ext.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PB3ViewHideInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PB3ForceUpdate

typedef GPB_ENUM(PB3ForceUpdate) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3ForceUpdate_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3ForceUpdate_ForceZero = 0,
  PB3ForceUpdate_ForceTrue = 1,
  PB3ForceUpdate_ForceFalse = 2,
};

GPBEnumDescriptor *PB3ForceUpdate_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3ForceUpdate_IsValidValue(int32_t value);

#pragma mark - Enum PB3HasInstall

typedef GPB_ENUM(PB3HasInstall) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PB3HasInstall_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PB3HasInstall_InstallZero = 0,
  PB3HasInstall_InstallTrue = 1,
  PB3HasInstall_InstallFalse = 2,
};

GPBEnumDescriptor *PB3HasInstall_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PB3HasInstall_IsValidValue(int32_t value);

#pragma mark - PB3VersionExtRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PB3VersionExtRoot : GPBRootObject
@end

#pragma mark - PB3GetLastVersionReq

typedef GPB_ENUM(PB3GetLastVersionReq_FieldNumber) {
  PB3GetLastVersionReq_FieldNumber_Version = 1,
  PB3GetLastVersionReq_FieldNumber_Platform = 2,
};

@interface PB3GetLastVersionReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

/** v050新增，平台 iOS/Android */
@property(nonatomic, readwrite, copy, null_resettable) NSString *platform;

@end

#pragma mark - PB3GetLastVersionRes

typedef GPB_ENUM(PB3GetLastVersionRes_FieldNumber) {
  PB3GetLastVersionRes_FieldNumber_Version = 1,
  PB3GetLastVersionRes_FieldNumber_ForceUpdate = 2,
  PB3GetLastVersionRes_FieldNumber_Remark = 3,
  PB3GetLastVersionRes_FieldNumber_Pkg = 4,
  PB3GetLastVersionRes_FieldNumber_HasInstall = 5,
  PB3GetLastVersionRes_FieldNumber_Date = 6,
};

@interface PB3GetLastVersionRes : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@property(nonatomic, readwrite) PB3ForceUpdate forceUpdate;

@property(nonatomic, readwrite, copy, null_resettable) NSString *remark;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pkg;

@property(nonatomic, readwrite) PB3HasInstall hasInstall;

/** 日期 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *date;

@end

/**
 * Fetches the raw value of a @c PB3GetLastVersionRes's @c forceUpdate property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3GetLastVersionRes_ForceUpdate_RawValue(PB3GetLastVersionRes *message);
/**
 * Sets the raw value of an @c PB3GetLastVersionRes's @c forceUpdate property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3GetLastVersionRes_ForceUpdate_RawValue(PB3GetLastVersionRes *message, int32_t value);

/**
 * Fetches the raw value of a @c PB3GetLastVersionRes's @c hasInstall property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t PB3GetLastVersionRes_HasInstall_RawValue(PB3GetLastVersionRes *message);
/**
 * Sets the raw value of an @c PB3GetLastVersionRes's @c hasInstall property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPB3GetLastVersionRes_HasInstall_RawValue(PB3GetLastVersionRes *message, int32_t value);

#pragma mark - PB3InstallReportReq

typedef GPB_ENUM(PB3InstallReportReq_FieldNumber) {
  PB3InstallReportReq_FieldNumber_Version = 1,
  PB3InstallReportReq_FieldNumber_Device = 2,
};

@interface PB3InstallReportReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@property(nonatomic, readwrite, copy, null_resettable) NSString *device;

@end

#pragma mark - PB3InstallReportRes

@interface PB3InstallReportRes : GPBMessage

@end

#pragma mark - PB3GetViewHideInfoReq

typedef GPB_ENUM(PB3GetViewHideInfoReq_FieldNumber) {
  PB3GetViewHideInfoReq_FieldNumber_Id_p = 1,
};

@interface PB3GetViewHideInfoReq : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@end

#pragma mark - PB3GetViewHideInfoRes

typedef GPB_ENUM(PB3GetViewHideInfoRes_FieldNumber) {
  PB3GetViewHideInfoRes_FieldNumber_Info = 1,
};

@interface PB3GetViewHideInfoRes : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PB3ViewHideInfo *info;
/** Test to see if @c info has been set. */
@property(nonatomic, readwrite) BOOL hasInfo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
